### ISSUE TITLE
Can you do a javascript version for all your projects

### ISSUE THREAD

**Issue by hakanerensen112** [mcstatus-io/widget-server#2]
İ need a widget server and ping server but i cant get widget server to work and because ping server api server is codded with go
İ cant run these servers

Can you at least make api server and ping server compatible with javascript

Thx

**Comment by PassTheMayo** [comment]
There is no way to make these "compatible" with JavaScript without completely rewriting them in the language. There is a reason the ping server is written in Go, because it's very efficient for working with streams. I won't be rewriting the ping server, nor do I have any plans for that at this time.

What issues are you having with trying to set up the ping server for yourself?
